AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: 'aws-sqs-lambda-trigger-test

  Sample SAM Template for aws-sqs-lambda-trigger-test

  '
Globals:
  Function:
    Timeout: 60
Resources:
  ReceiveMessageFromTestQueue:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ReceiveSQSMessage
      Description: Receive a message from sqs queue
      Role: arn:aws:iam::508701674840:role/aws-sqs-lambda-role
      CodeUri: s3://venu-sam-package/61191243d756521efaec5e8df9b50003
      Handler: main.lambda_handler
      Runtime: python3.8
      Events:
        TestQueue:
          Type: SQS
          Properties:
            Queue: arn:aws:sqs:us-east-1:508701674840:TestQueue.fifo
            BatchSize: 10
Outputs:
  HelloWorldApi:
    Description: API Gateway endpoint URL for Prod stage for Hello World function
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/
  HelloWorldFunction:
    Description: Hello World Lambda Function ARN
    Value:
      Fn::GetAtt:
      - HelloWorldFunction
      - Arn
  HelloWorldFunctionIamRole:
    Description: Implicit IAM Role created for Hello World function
    Value:
      Fn::GetAtt:
      - HelloWorldFunctionRole
      - Arn
